### ISSUE TITLE
ocis compose file, missing 

### ISSUE THREAD

**Issue by felixboehm** [owncloud-docker/compose-playground#8]
This is a working compose file example, supporting to configure the IP
Yet I don't see a clean way to pass the IP to the `/config/identifier-registration.yaml`

So for now, the 'localhost' needs to be replaced with BASE_IP in the `/config/identifier-registration.yaml`.

IP defaults to localhost
and can be set in .env file, like `BASE_IP=192.168.1.97`

```
version: '3.4'
services:
  ocis:
    depends_on:
    - redis
    environment:
      PROXY_HTTP_ADDR: 0.0.0.0:9200
      KONNECTD_ISS: https://${BASE_IP:-localhost}:9200
      PHOENIX_OIDC_AUTHORITY: https://${BASE_IP:-localhost}:9200
      PHOENIX_OIDC_METADATA_URL: https://${BASE_IP:-localhost}:9200/.well-known/openid-configuration
      PHOENIX_WEB_CONFIG_SERVER: https://${BASE_IP:-localhost}:9200
      REVA_OIDC_ISSUER: https://${BASE_IP:-localhost}:9200
      REVA_STORAGE_OWNCLOUD_REDIS_ADDR: redis:6379
      KONNECTD_IDENTIFIER_REGISTRATION_CONF: /config/identifier-registration.yaml
      KONNECTD_TLS: 0
      OCIS_LOG_LEVEL: debug
      KONNECTD_LOG_LEVEL: debug
    image: owncloud/ocis:latest
    ports:
    - published: 9200
      target: 9200
    restart: always
    volumes:
    - ${PWD}/ocis-play/config:/config:rw  
    - ${PWD}/ocis-play/data:/var/tmp/reva/data:rw
  redis:
    environment:
      REDIS_MAXCONN: '10000'
    image: redis
    restart: always
```
